### ISSUE TITLE
Modify the Miner to include different B types

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-asct-reporter#101]
In a recent meeting with Katy, she revealed that there are going to be more B types, namely,
- Lipids (BL)
- Metalloids (BM)
- Proteoforms (BF)

Currently there is support for only Gene and Protein. 

### Work items
- Modify the ASCT+B Data miner to incorporate these
- Shouldn't be much of a change, just add a few keys to the interface and the key dict

Should return,
```
...
...
biomarkers_lipids: [],
biomarkers_meta: [],
biomarkers_prot: []
```

in the response along with the other data

**Comment by vutukuriajay2241** [comment]
Is this just changes to miner or we need to work on frontend as well?

**Comment by bherr2** [comment]
It would effect the frontend as well, but should be fairly minor. Just follow the model with how it was done for Genes (BG) and Proteins (BP).

**Comment by vutukuriajay2241** [comment]
Sure

**Comment by bherr2** [comment]
We may need to dig around for how the miner is deployed. At some point we'll move that over to AWS, but for now its running on heroku (somehow).
