### ISSUE TITLE
Switch to Draft Lung Table

### ISSUE THREAD

**Issue by kebelhar** [hubmapconsortium/ccf-asct-reporter#111]
We need to make the new DRAFT v1.5 table the only LIVE lung ASCT+B table accessible in the ASCT+B Reporter. 

Can you remove access to the Lung_v1 tab in the Reporter: 
url: [Lung_v1](https://docs.google.com/spreadsheets/d/1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0/edit#gid=925712902)

and make the tab called  Lung_v1.5_DRAFT the only version live in the Reporter as soon as possible and let us know when this has been done? 
url: [Lung_v1.5_DRAFT](https://docs.google.com/spreadsheets/d/1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0/edit#gid=1824552484)

The dropdown to select organ needs to include DRAFT in the name.

**Comment by bherr2** [comment]
Merged via #112
