### ISSUE TITLE
horizontal scroll bar 

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#122]
From infoccf@indiana.edu "Contact us": Gloria Pryhuber <Gloria_Pryhuber@URMC.Rochester.edu> writes:
Hi, thank you for wanting to contact us! This is an auto-generated body template. Below are a list of possible subjects, 

2. Feature request for the reporter.      
Hi, It seems that there is a vertical scroll bar but not a horizontal scroll bar in the (lung) reporter.  For a table/tree as wide as the lung this is really necessary. 
Possible to add?  Or maybe its there and I’m missing how to see/use it?
Thanks

**Comment by bherr2** [comment]
@macvogelsang any progress on this?

**Comment by macvogelsang** [comment]
@bherr2 Got stuck on it a few weeks ago and moved to other things. I can pick it back up after I complete my other issue or we can assign it to someone else.
