### ISSUE TITLE
Issue with Public google sheet link source: Browser URL vs Sharing Get Link

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#123]
Another ASCT+B reporter question via infoccf@indiana.edu: From Gloria Pryhuber; I tested and verified this is the issue. Ran it by Bruce. Bruce says "Because the get link doesn't include the gid which identifies which tab of the sheet to use. I'd need to look into whether we can default to gid=0 if we're given a link of that different form. Yeah, we probably have to check for that variant and pop up a reminder that they must use the url from the web browser bar and not the get link feature." 
If I make a ASCT+B templated new organ to use the playground feature and I make the sheet “anyone with link”, if I copy the link provided to use for upload, it gives this error, but if I copy the url from the browser address bar for upload, it works fine.  Why should this produce this type of issue?  Shouldn’t the “copy link” from share dialog be the same?  This is not clear and had a user (Gloria P) submit another question like this.
Url from web browser bar: https://docs.google.com/spreadsheets/d/1XwI0_QbQxZ0lvoQI-5N5HPUJAWGCxB5-f8OlQfg6cjg/edit#gid=0
URL from “get link” in share: produces error in reporter: https://docs.google.com/spreadsheets/d/1XwI0_QbQxZ0lvoQI-5N5HPUJAWGCxB5-f8OlQfg6cjg/edit?usp=sharing
Error!
The visualization could not be rendered due to some errors. Below mentioned are a list of problems that could’ve occurred.
The data version that you selected is depricated for the sheet. Click on this link to see the depricated sheets.
The format of the data didn’t match the format of the master tables.
Network issues.
To report this issue, please reach out to us, here.
HttpErrorResponse (Status: 500) (edited)

**Comment by emquardokus** [comment]
@bherr2   6-15-2021 Had another user Andrea Radtke have same "error" as Gloria P. "The visualization could not be rendered due to some errors. Below mentioned are a list of problems that could’ve occurred.
The data version that you selected is depricated for the sheet. Click on this link to see the depricated sheets.
The format of the data didn’t match the format of the master tables." We minimally need to update documentation to clarify to use browser url not the shared link.

**Comment by bherr2** [comment]
We now have a gentle push via #144 but this needs to be made more explicit, ideally where they copy/paste the sheet URL so that they don't even hit the error, they see what they need to do. @emquardokus do you think you could comment on what kind of text/prompts might be useful from a User's perspective on this?

**Comment by emquardokus** [comment]
Current Compare Dialog is "Enter Google Sheet Link"  instead "Enter Browser url address for Google Sheet"
Current Instructions provided at top of Compare Dialog is "Instructions
Through this feature, you can compare your own data by pasting the Google Sheet link of your data in the fields mentioned below. Multiple data sources can be added by clicking on the '+ Add' button at the bottom.cIn order to successfuly link your sheet, make sure the sheet has public access (Anyone with the link can view).
Please make sure your data follows the appropriate data format, see template. "
    
Substitute "pasting the Google Sheet link" with "pasting the Browser url address for the Google sheet"
Substitute: "In order to successfuly link your sheet, make sure the sheet has public access (Anyone with the link can view)." (NOTE typo successfuly")  with "in order to successfully link your sheet, make sure the sheet has public access by selecting Share--> Get link--> selecting "Anyone with the link" option and "Viewer" privileges, select Done to save."

**Comment by emquardokus** [comment]
Current Playground Dialog is "Google Sheet Link Please input your public Google Sheet Link."  instead "Google Sheet Link Please Enter Browser url address for your public Google Sheet"

**Comment by bherr2** [comment]
@vutukuriajay2241 this is reopened. see the two changes that @emquardokus requested.

**Comment by vutukuriajay2241** [comment]
Ohh. I looked at it now 😅
