### ISSUE TITLE
Convert Azimuth Atlas to ASCT+B tables

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-asct-reporter#129]
Parent EPIC: #127

Tasks:

- [x] Download cell type annotations hierarchy in spleen visualization shown [here](https://portal.hubmapconsortium.org/preview/cell-type-annotations)
- [x] Convert [JSON data](https://s3.amazonaws.com/vitessce-data/0.0.31/master_release/satija/2dca1bf5832a4102ba780e9e54f6c350.cell-sets.json) from spleen visualization to ASCT+B table format with CT as AS.
- [x] Generate ASCT+B visualization from the [ASCT+B table](https://docs.google.com/spreadsheets/d/1NnofLP2ieaTLjIiykk_8BaS1oCF3JW6_t6mrmqoRTWo/edit#gid=362249431) generated in the previous step 
- [x] Repeat the same steps above but with Azimuth's [Seurat Rds reference data](https://azimuth.hubmapconsortium.org/references/) for each organ that is available (code available [here](https://github.com/DarshalShetty/asctb-azimuth-data-comparison))
  - [x] Explore the option to convert Seurat Rds files to h5ad format which could be used by Python's ScanPy library by following the instructions [here](https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html)
  - [x] Explore the option to directly work on the Rds data in R with the help of the `table` function mentioned by Rahul and Jaison.
- [x] Remove organ name as first column
- [x] Include cell counts in generated table 
- [x] Add ontology ID columns for cell types
- [x] ~Perform the same data extraction as Azimuth's reference files but now with demo datasets.~ (moved to #181)

**Comment by DarshalShetty** [comment]
Waiting for Jaison's response on how to get ontology IDs for cell types from Azimuth reference files

**Comment by DarshalShetty** [comment]
I received the ontology data from Jaison and added ID and LABEL columns based on that data. Further progess can be tracked at #163.

**Comment by DarshalShetty** [comment]
@bherr2 Should I create a new issue for the new tasks that I have added?

**Comment by bherr2** [comment]
Yes, please
