### ISSUE TITLE
Make a cool dev team name

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-asct-reporter#155]
Our dev teams are usually named using a color and shape/animal. For instance `Blue Dino` and `Green Rhino` (now defunct) are two dev team names we used in the past. Post suggestions here!

**Comment by emquardokus** [comment]
Golden Ibex 
Ibex animal is a mountain goat type of creature; however, coincidentally, it is also the name of a molecular imaging technique used by one of our new collaborators Andrea Radtke from the Affinity reagents WG and they are collaborating heavily to extend use cases for using the ASCT+B Reportr to develop tissue specific antibody panels that will become another column or two or three in the tables.
**Reason selected:** An Homage to our newest ASCT+B WG collaboration Andrea Radtke uses a uses a molecular imaging technique called Ibex (Iterative bleaching extends multiplexity)
Paper citation:  Radtke, Andrea J., Evelyn Kandov, Bradley Lowekamp, Emily Speranza, Colin J. Chu, Anita Gola, Nishant Thakur, et al. 2020. “IBEX: A Versatile Multiplex Optical Imaging Approach for Deep Phenotyping and Spatial Analysis of Cells in Complex Tissues.” Proceedings of the National Academy of Sciences 117 (52): 33455. https://doi.org/10.1073/pnas.2018488117.

“Iterative bleaching extends multiplexity” (IBEX) uses an iterative staining and chemical bleaching method to enable high-resolution imaging of >65 parameters in the same tissue section without physical degradation."

**Comment by bherr2** [comment]
I like Ibex! Need another color ([list of colors](https://htmlcolorcodes.com/color-names/)) to help it roll off the tongue :-P

- Golden Ibex?
- Indigo Ibex?
- Orchid Ibex?
- Green Ibex?
- Aqua Ibex?

Also in search of a cool free (as in freedom and beer :beer:) ibex image to color and use.

**Comment by bherr2** [comment]
`Indigo Ibex` is my current favorite

**Comment by emquardokus** [comment]
I was hoping for symbolic Gold, maybe Silver as Gold Medal  team.  
Indigo was my first choice for color before I settled on Ibex though :-)

**Comment by emquardokus** [comment]
Top Ibex is FUN :-)
Bottom Ibex is more serious looking...

**Comment by bherr2** [comment]
For reference, here is our other Dev Team's logo (Blue Dino):

![blue-dino-480](https://user-images.githubusercontent.com/34098595/123287601-d5375900-d4dc-11eb-8de1-aae1ac769a65.png)

And the now defunct, Green Rhino:

![green-rhino](https://user-images.githubusercontent.com/34098595/123287663-e41e0b80-d4dc-11eb-9aa3-916cdb1353e4.png)

**Comment by emquardokus** [comment]
winner? 
![123284033-edf23f80-d4d9-11eb-9609-ef050fffcda0](https://user-images.githubusercontent.com/47257000/123296020-44fd1200-d4e4-11eb-9529-d7be3e472c75.png)

**Comment by bherr2** [comment]
We'll have a final vote at stand-up tomorrow :-)

**Comment by DarshalShetty** [comment]
![red_ibex](https://user-images.githubusercontent.com/10777923/123446253-b30a0d80-d5a6-11eb-8c8f-252efc73fc8d.png)

I was thinking since we already had green and blue teams, red would complete the primary color set. Also red rolls off the tongue easily :stuck_out_tongue:

**Comment by bherr2** [comment]
Indigo Ibex wins by majority vote :-)

**Comment by katyb** [comment]
What a great red bull
K

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by emquardokus** [comment]
@katyb ibex (see my original post suggesting ibex)
There's deeper meaning :-) directly related to our collaboration with Neil Kelleher AR-WG and Andrea Radtke

**Comment by bherr2** [comment]
Per majority vote, the dev team is now known as `Indigo Ibex`! :goat: :partying_face: 
![ibex-cartoon](https://user-images.githubusercontent.com/34098595/123834529-82dbab00-d8d5-11eb-8320-ca6d1a5038fe.png)
