### ISSUE TITLE
Update and expand Data Format Documentation

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-asct-reporter#156]
Source data format readme is in [projects/v2/src/assets/docs/data-format/README.md](https://github.com/hubmapconsortium/ccf-asct-reporter/blob/main/projects/v2/src/assets/docs/data-format/README.md). This needs to be expanded to include the updates coming down the pipe (multi-level cell types, new biomarkers, FTUs, etc.). And also needs to be very readable by new users.

**Comment by bherr2** [comment]
From Katy @katyb

> Where can I find current docu of the ASCT+B table format? We need something similar to

![image](https://user-images.githubusercontent.com/34098595/123158203-7b318780-d439-11eb-897b-280037964154.png)

> A brief explanation of each of the top ten rows and each of the column in MASTER.
> k

**Comment by emquardokus** [comment]
I can work on this for new version 2 table additions and enhancements.
