### ISSUE TITLE
Use new column names for biomarkers

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-asct-reporter#160]
Biomarker columns will now be named according to the mapping below.

* [x] In the ASCT+B API support the old naming B`x`, but also support the new mapping as below. This should be a server only change.
* [x] Update data format markdown docs to reflect this.

Mapping:

- Proteoform → BProteoform (NEW)
- Lipid —> BLipid (NEW)
- Metabolite —> BMetabolite (NEW)
- Protein  —> BProtein (Renamed from OLD BP)
- Gene —>BGene (Renamed from OLD BG)

**Comment by bherr2** [comment]
This should be as easy as adding new mappings to: https://github.com/hubmapconsortium/ccf-asct-reporter/blob/main/asctb-api/src/index.ts#L69-L78

**Comment by vutukuriajay2241** [comment]
Done

**Comment by vutukuriajay2241** [comment]
will give a commit in 5 mins
