### ISSUE TITLE
Add ID and LABEL to Azimuth ASCT+B Tables

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-asct-reporter#163]
* [x] Add `CT/n/ID`s (the Cell Ontology ids, which should have form: CL:nnnnnn)
* [x] Add `CT/n/LABEL`s (which is the RDFS Label associated with the ontology term (ID)). There is a SPARQL endpoint for grabbing labels that @macvogelsang has been using for descriptions that he could send you a snippet if/when you need it.

**Comment by DarshalShetty** [comment]
CSVs with required additional columns can be viewed [here](https://darshalshetty.github.io/asctb-azimuth-data-comparison/).  @bherr2 can you have a look and provide feedback? I'll ask Katy and Ellen to do the same in an email after I've added documentation.

**Comment by bherr2** [comment]
The data looks right. What is the provenance of the other data files in data/? Why are there asct+b tables in there?

**Comment by DarshalShetty** [comment]
-  ```asctb_tables/``` is where the final asct+b tables are generated
- ```azimuth_references/``` is for storing the reference RDS files downloaded from [Azimuth's references page](https://azimuth.hubmapconsortium.org/references/). The files in here are one of the inputs for the data conversion script.
- ```azimuth_ct_tables/``` is the data that Jaison provided me which maps the cell types in reference files to their respective ontology IDs and labels. This is another one of the inputs for the conversion script
- ```organ_data.json``` is a config file which stores the names of the available organ data and their corresponding cell hierarchy column names in the reference RDS files. This is also an used as input to the conversion script.

Except ```azimuth_ct_tables/```, the purpose of all the other files in the ```data/``` directory is mentioned in the readme documentation.

**Comment by bherr2** [comment]
* asctb_tables absolutely should not be stored there. This is a major syncing issue. If you absolutely need it for development, add the directory to `.gitignore`. The generated data should only go to github pages and only via GitHub Actions (reproducibility + traceability). 
* What is the provenance of Jaison's data? How can this be reproduced and/or expanded to other organs in the future? Not a fan of one-off solutions.

**Comment by DarshalShetty** [comment]
- Sure, I'll add it to gitignore.
- Jaison's data is from what is currently being displayed on the [Azimuth references page](https://azimuth.hubmapconsortium.org/references/). He just sent a CSV file that contained the same data that is being displayed in the tables shown in the screenshot below. I don't think they are using an API to populate the tables on this webpage and my guess would be that they are manually editing a file to generate the data in the table. Should I ask them to provide an API for this data? If they had an API then I wouldn't have the need to maintain the ```organ_data.json``` config file too.
![image](https://user-images.githubusercontent.com/10777923/124026155-5308d200-d9bf-11eb-86d0-f2b1c01bf541.png)

**Comment by bherr2** [comment]
Yes, please ask them for details. Ideally there is an API or other ways to reproduce it, but having links to documentation on how/when this happens would be great.

**Comment by bherr2** [comment]
I looked at the changes. Looks good except ;ne thing that needs changed: you are formatted the IDs like: `CL_XXXX` but they need to be `CL:XXXX`

**Comment by DarshalShetty** [comment]
Should I do the same for the Uberon IDs?

**Comment by bherr2** [comment]
Yes, all IDs should have the form `${ONTOLOGY}:${ID}`

**Comment by DarshalShetty** [comment]
@bherr2 Could you review my latest push?

**Comment by bherr2** [comment]
Looks good. Works in the ASCT+B reporter now.

**Comment by bherr2** [comment]
@emquardokus can you review the details of the CSV files? I'm not an SME and want to make sure what he's generating makes sense to you as well.
You can view them on github here: https://github.com/DarshalShetty/asctb-azimuth-data-comparison/tree/gh-pages or download from https://darshalshetty.github.io/asctb-azimuth-data-comparison/
