### ISSUE TITLE
Ability to load CSV URLs

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-asct-reporter#165]
* [x] Create a new route on the ASCT+B API that can take a CSV URL and return the parsed JSON
* [x] Wherever a Google Sheet Browser URL can be entered, a CSV URL should be able to be entered

**Comment by bherr2** [comment]
Let's make the route `/v2/csv` which takes a POST (not GET) request with body being the CSV URL to GET from. The current server code should not need to be refactored (much?) other than adding a new route. Client-side code will need to determine if they pasted a Google Sheets URL. If its not, send the URL to the /v2/csv route and assume its a URL to a CSV to GET.

**Comment by vutukuriajay2241** [comment]
I tried to send the url string as headers parameter as GET request

**Comment by vutukuriajay2241** [comment]
What do you think on that?

**Comment by bherr2** [comment]
POST is better

**Comment by vutukuriajay2241** [comment]
Ok Will makes those changes
