### ISSUE TITLE
 UNIQUE AS-CT combinations per organ

### ISSUE THREAD

**Issue by vutukuriajay2241** [hubmapconsortium/ccf-asct-reporter#173]
This feature needs to be added in Report tab under general Stats.

Computing rule.

- Each row in the MASTER table is an AS-CT combination.

**Comment by bherr2** [comment]
@katyb is this literally the number of data rows in the sheet?

**Comment by emquardokus** [comment]
@bherr2 the last AS with CT for each row will be the AS-CT combination.
If the 3 level CT is implemented in v2 ASCT+B table, then it would still be last AS -CT/1, CT/2, CT/3 for each row in table
