### ISSUE TITLE
Map antibodies to biomarker proteins in ASCT+B tables

### ISSUE THREAD

**Issue by DarshalShetty** [hubmapconsortium/ccf-asct-reporter#187]
Given the list of antibodies in the "Antibodies Used by HuBMAP" of  [this spreadsheet](https://drive.google.com/file/d/1QIhVmPqds7v0ey4nUlYwM6lR-DJZjPLY/view?usp=sharing), find the corresponding biomarker proteins present in the ASCT+B master tables.

Steps:
- [ ] Gather unique HGNC IDs for biomarker proteins across all body organ sheets in the [ASCT+B master tables](https://docs.google.com/spreadsheets/d/1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0/edit?pli=1#gid=2034682742)
- [ ] Get UniProt IDs corresponding to HGNC IDs using [this API](https://www.genenames.org/help/rest/)
- [ ] Join the Antibodies spreadsheet with the unique biomarker proteins gathered in step 1using the HGNC to UniProt correspondence fetched in step 2.

**Comment by DarshalShetty** [comment]
@emquardokus 

I had a few questions:
- Should I gather unique biomarker proteins from a particular version of tables or should I just gather them from across all sheets present in the master table spreadsheet?
- During joining, should I also include the name of the sheet in which the biomarker protein was found in? Any other information related to the biomarker protein that I should include?

**Comment by emquardokus** [comment]
@DarshalShetty @bherr2  @katyb 
please use the tabs color coded in purple and named organ v1.5; these are the DOI v1 tables that have the updated row 11 headers to match the newly supported biomarkers etc.
For completeness, YES, probably a good idea to point to which ASCT+B table you are fetching information from. The biomarker protein names are 1:1 correspondence with genes.  This may change for proteoforms biomarker, but we don't have this yet.
