### ISSUE TITLE
Comparison feature: Criteria used to deterimne New AS, CT compared to Master tables

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#188]
@bherr2 @katyb 
When testing out Reporter v2.2, I realized that compare feature was only determining "new AS" based on lexical match and not based on uberon IDs. 

If both comparison table and master tables have Uberon IDs, then uberon ID matching should be used as primary criteria for new vs same comparison.

If no Uberon ID is given in compared table to Master, then lexical matching might be the secondary criteria.

Please use this control true partonomy spleen  ASCT+B table where I verified every part of relationship depicted in a row to compare to the SME authored DOI v1 Spleen table. Only the Uberon labels were used for both AS/1 and AS/1/LABEL fields in this control table:
SpleenPartonomyCellTypology07-09-2021:
https://docs.google.com/spreadsheets/d/1YhyYabDsZlVjZRKqUWhP3u6_mWU3neHP/edit#gid=91340060
vs
ASCT+B_Tables_Standard_Format_3-24-2021 Spleen_v1 tab:
https://docs.google.com/spreadsheets/d/1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0/edit#gid=22580074

Examples shown in comparison of spleen partonomy table vs Master spleen table: 
dashed circle = new in partonomy table compared to master table
1) splenic pulb (master) vs spleen pulp--> both have uberon id 1000023
2) trabeculae (master) vs trabecula of spleen -> both have uberon id 0001265
3) red pulp (master) vs red pulp of spleen -> both have uberon id 00001250
many other examples ...

<img width="1440" alt="Screen Shot 2021-07-14 at 12 29 41 AM" src="https://user-images.githubusercontent.com/47257000/125561420-7b1c69ab-359d-4077-bbed-4b4645a8310e.png">

**Comment by bherr2** [comment]
@emquardokus we've merged code to address this issue. I tested it myself on data that needed it, but please test yourself on the staging server to see if this meets your needs. https://ccf-asct-reporter.netlify.app/

Let us know if this issue can be closed with these new changes.
