### ISSUE TITLE
Generate process logs

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-asct-reporter#2]
# Overview 
Process logs/reports must be generated and shown to the user on the web application to make them aware of what operations are taking place. Data with their respective tags that could potentially be displayed on the reports are given below.

## Tags
1. [SUCCESS]: Operation was successfully completed.
2. [WARNING]: Operation was partially successfully completed that could meddle with the functionality of the visualization.
3. [ERROR]: Operation wasn't successfully completed that could meddle with the functionality of the visualization.

## Data
> Needs more work on coming up with various fields to check for.

These are some examples of what could be shown on the report logs.

1. Data fetch successfully/unsuccessfully.
2. Data refreshed.
3. Data  successfully/unsuccessfully processed.
4. FIELD missing.

**Comment by bherr2** [comment]
Use icons from Angular Material rather than text labels. See https://material.angular.io/components/icon/overview and https://material.io/resources/icons/?search=warning&icon=warning&style=baseline

**Comment by hrishikeshpaul** [comment]
@bherr2 Yes, I thought about using icons for the labels. I have some mockups with those put up as issues.
