### ISSUE TITLE
[staging] When selecting a structure in the Search, the view no longer automatically jumps to that selected structure

### ISSUE THREAD

**Issue by macvogelsang** [hubmapconsortium/ccf-asct-reporter#201]
How to reproduce:
1) Go to the staging url https://ccf-asct-reporter.netlify.app/vis?sheet=bone_marrow&version=latest
2) Search for a structure that's off screen (i.e. promocyte)
3) See that the view doesn't scroll there automatically (but in production it does)

**Comment by vutukuriajay2241** [comment]
@macvogelsang  I think it broke when we add horizontal scroll to the visualization.
