### ISSUE TITLE
Extension of CT levels to unlimited like AS levels

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#218]
Much like the Anatomical structures (AS), there are different numbers of levels of cell types (CTs).  It seems like this should not be too difficult to do since the header format would be the same as existing, just be able to go out beyond 3 levels.

**Comment by bherr2** [comment]
I believe this is the case currently. It's just that in the visualization, they are not shown as a tree. @vutukuriajay2241 can you confirm that we are not limiting CT to just 3 levels?

**Comment by vutukuriajay2241** [comment]
Yes @bherr2 and @emquardokus , They are not limited to just 3 Levels.

**Comment by emquardokus** [comment]
@bherr2 @vutukuriajay2241 This is fantastic!  Katy was under a different impression and has been stating only 3 CT levels.
Now that I know for sure we can support varying levels (which only made sense to me) I will make sure table authors are aware of this!  THANKS!!

**Comment by bherr2** [comment]
Cool. Closing this issue then. Let us know if you have any trouble.
