### ISSUE TITLE
Integrate Google Analytics

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-asct-reporter#22]
# Google Analytics

Receiving feedback from what users interact with and use the most has always been important. Through Google Analytics, we hope to track the usage on the Reporter so as to get insights on what features and functionalities need to be improved upon

## Getting Started
1. Use an NPM package from here: https://www.npmjs.com/package/ngx-google-analytics OR 
2. A details guide as to how to set it up - https://medium.com/madhash/how-to-properly-add-google-analytics-tracking-to-your-angular-web-app-bc7750713c9e
3. For now use your own GCP GA ID. (It's free)

## How to use GA with Vega? 
Use the code snippet below to get the value from signals of the Vega graph,
```
let signalValue = this.treeView.signal('node__click')
this.treeView.runAsync();
console.log(signalValue)
```
Check out the [docs](https://vega.github.io/vega/docs/api/view/) for more info.

## Event Tracking

https://docs.google.com/spreadsheets/d/1nY89jasZqSWtKDwI0izXOsRZqdyqOjsGcRIPPvVEy-Y/edit#gid=0 This google sheet will have all the events that need to be tracked.

> This sheet is under constant upgrades.

**Comment by hrishikeshpaul** [comment]
@bherr2 please review this!

**Comment by knikharg** [comment]
Change  **gtag('config', 'XX-XXXXXXXXX-X');**  with your tracking code to test
