### ISSUE TITLE
Integrating Google Analytics  into Reporter

### ISSUE THREAD

**Issue by vutukuriajay2241** [hubmapconsortium/ccf-asct-reporter#250]
Need to discuss with Andi what needs to be included in the reporter.

**Comment by andreasbueckle** [comment]
Goal: For Playground and for Comparison, log:
* #AS
* #CT
* *#B 

Also, log:
* which organs were selected at start-up (might already be logged by default)
* and which table version
![image](https://user-images.githubusercontent.com/22821046/140419794-a1845ecb-e53c-4eb7-bbb4-a4106267837e.png)

We already log:
* interactive legend on the left (also add values)
* What format the user exports in (PNG, SVG, etc.)

**Comment by vutukuriajay2241** [comment]
- Improve organ selection counts
- graph_node_select, graph_node_click
- node selection details
-
