### ISSUE TITLE
Small intestine visualization 

### ISSUE THREAD

**Issue by vutukuriajay2241** [hubmapconsortium/ccf-asct-reporter#275]
Reporter is throwing error when trying to visualize small intestine

**Comment by emquardokus** [comment]
@vutukuriajay2241  looks OK to me.
<img width="695" alt="Screen Shot 2021-11-16 at 11 53 53 PM" src="https://user-images.githubusercontent.com/47257000/142137145-7d7e2c6b-323d-4055-bd26-2230bdf1ed59.png">
..
