### ISSUE TITLE
BUG: Problem with Protein Biomarkers and their plus or minus designation WRONG in Vis for CT, correct in table

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#277]
@bherr2 @katyb 
I was working on tables and Andrea Radtke and I noticed when visualizing Lymph node tables that ASCT+B tables are correct, but visualization is WRONG for the protein biomarkers for plus or minus designation.

I have now also checked this for all other tables and this is true of all tables. This is bad. 

How is Reporter handling plus or minus protein markers?

From flow cytometry data and imaging data, protein markers that are both positive and negative define/characterize a cell type.  It's just as important to know that a particular protein is ABSENT from a CT as those that are PRESENT especially for immune cells to determine what stage of their differentiation pathway they are on.

How is the reporter handling CD8+ vs CD8- when tallying markers and when visualizing?

Lymph node table has "Naive CD8+ T-cell" and visualization shows CD8-, the table rows 48 and 72  itself shows CD8+ for both and clearly from name definitely should be showing CD8+---we do not understand how it’s showing something other than what exists in table? : 

<img width="1233" alt="Screen Shot 2021-11-16 at 2 57 55 PM" src="https://user-images.githubusercontent.com/47257000/142140430-2d03b4bd-3a9b-4d31-94e3-a43ca3f2f7e4.png">

<img width="561" alt="Screen Shot 2021-11-07 at 3 31 29 PM" src="https://user-images.githubusercontent.com/47257000/142140399-30c4a26e-2838-48ff-bef2-aa9cb8d9cd1b.png">

**Comment by bherr2** [comment]
@vutukuriajay2241 please prioritize this task asap. Remove +/- from biomarker node labels and color code edges by presence of +(green)/-(red)? Feel free to figure out a better color.

CC @katyb as we are getting pushback from SMEs

**Comment by emquardokus** [comment]
Received email from someone with roche.com address also mentioning this problem; out of all issues, this is a HUGE one to resolve as soon as possible; spoke with Bruce at 9 am this morning detailing issue again.

The data tables are correct, but as per conversation with Ajay, the first instance of a protein biomarker is what ends up being used for all in the visualization as opposed to taking the real designation from the ASCT+B data table and using directly.  Huge problem.

From: Bian, Yuying <yuying.bian@roche.com>
Sent: Wednesday, December 8, 2021 4:33:52 AM (UTC-05:00) Eastern Time (US & Canada)
To: HuBMAP CCF Info <infoccf@indiana.edu>
Subject: [External] About the ASCT B Reporter!

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.
 
Hi there,  
 
Thank you for the amazing work of the ASCT B Reporter and it really provides many informative information and intuitive visualization for our users.
To use the ASCT B Reporter better, I have some questions about the Reporter and would like to discuss them with you.
 
The first question is about the protein Biomarker. When I checked cell types and biomarkers of cells in blood, there are some protein Biomarkers that seem not to be consistent with some publications. For example, CD3 is T cell surface marker which should have a high expression on the T cell surface. But when clicking CD4 naive cells on the Reporter, it showed 'CD3-', representing CD4 naive cells have low expression of CD3 on the cell surface. Also, CD45RA protein Biomarker showed 'CD45RA+' both in 'CD4 naive' and 'CD4 T cell memory, however, many papers mentioned that CD45RA had low expression and CD45RO highly expressed in T memory cells. I tried to find the dataset information about Blood data, but I didn't find information about it on the website (https://hubmapconsortium.org/hubmap-data/#). So do those biomarkers are bugs or maybe I have a wrong understanding about their expression on different blood cells?
 
The other question is about feature requests for the reporter , because the ASCT B Reporter has provided comprehensive data of different tissues, cell types, and biomarkers, it might be a great source or reference for further analysis and research. Is it possible to provide the expression level of gene or protein biomarkers? Like the histogram on Human Protein Atlas.
 
Hope I don't ask too much. Thank you for the amazing work again and look forward to your reply!
 
Best regards,
Yuying

**Comment by bherr2** [comment]
@Nikhil-lab I think you implemented this originally. Could you take a look at this today? Ajay is out today.

**Comment by bherr2** [comment]
Oh wait @Nikhil-lab , wrong issue  :grimacing:
