### ISSUE TITLE
BUG: mutliple CT hierarchy not displaying only CT/1

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#279]
@bherr2 @katyb 
I thought the mutliple CT hierarchy was supported now?  It's not showing up; instead all CT in hierarchy are showing as separate CT.

**Table:**
<img width="1295" alt="Screen Shot 2021-11-17 at 2 13 06 AM" src="https://user-images.githubusercontent.com/47257000/142154261-6686e393-6063-45c3-baab-799c51509b20.png">

**Vis**
<img width="885" alt="Screen Shot 2021-11-17 at 2 10 22 AM" src="https://user-images.githubusercontent.com/47257000/142151022-de7f94b1-97b8-490c-9e2f-c952243d69b3.png">

**Comment by bherr2** [comment]
The hierarchical display is not implemented yet. It only flattens the tree. You will see all nodes in a single list for the cell types.

**Comment by bherr2** [comment]
Closing this. #352 represents adding this feature.
