### ISSUE TITLE
BUG: Comparison feature report has column headers opposite to VIS output

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#288]
Comparing a table of biomarkers to the Lymph node v1.1 table, 4 biomarkers showed in the visualization as new denoted with hash outline around biomarkers, the rest were the same as in the table. 
When I went to reports--> compare tab-->download and opened table, it showed 4 biomarkers under column heading called "identical biomarkers" and all the rest under "new biomarkers". This should be the opposite. 
---
Here's url of google sheet https://docs.google.com/spreadsheets/d/1qLnwCdtU6H4pqHAfA1JtyVvvTw2Lewd_BgXYuQ0QAk4/edit#gid=1042015770

Compare this to Lymph node v1.1 ASCT+B table. 
---
See screen shots below: 
<img width="391" alt="Screen Shot 2021-12-02 at 1 26 55 AM" src="https://user-images.githubusercontent.com/47257000/144369510-25fbce77-6b20-460a-9163-370a780b98ff.png">
<img width="1131" alt="Screen Shot 2021-12-02 at 1 50 42 AM" src="https://user-images.githubusercontent.com/47257000/144372458-093a35da-2746-49c8-a539-724bc97dafdf.png">
<img width="1131" alt="Screen Shot 2021-12-02 at 1 51 05 AM" src="https://user-images.githubusercontent.com/47257000/144372463-648ce3f7-3552-4e21-8ea3-96f0a99a30d6.png">

**Comment by emquardokus** [comment]
@bherr2 I am pretty sure this had been fixed when it was closed back in early Dec because I had used it then, but as of tonight 1-19-2022 it appears to be back to the original WRONG version.
In other words, the comparison report download file has column A and B column headers reversed.  Column A says "Identical Biomarkers" and Column B says "New Biomarkers" ; however the content is opposite to what the Reporter visualization shows, which  is CORRECT.

**Comment by bherr2** [comment]
@emquardokus Can you try the staging version? https://ccf-asct-reporter.netlify.app/

**Comment by emquardokus** [comment]
> @emquardokus Can you try the staging version? https://ccf-asct-reporter.netlify.app/

@bherr2 It's wrong in both staging and production versions. Tried it out today.

**Comment by bherr2** [comment]
@Nikhil-lab please take note and fix asap.
