### ISSUE TITLE
BUG: Export to PNG does not work

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#289]
Tried exporting from ASCT+B reporter and Export to PNG would not work. 

Export to SVG works
Export to OWL/XML works
Everything except PNG works.

**Comment by emquardokus** [comment]
@vutukuriajay2241 I was able to download PNG tonight when I was working

**Comment by Nikhil-lab** [comment]
I cross verified both in development as well as production. Export to Png is working fine. Hence closing this issue
<img width="1440" alt="Screen Shot 2021-12-25 at 11 37 42 AM" src="https://user-images.githubusercontent.com/54205111/147389552-4625d018-deec-4d5f-9db3-c04f7c108901.png">

**Comment by vutukuriajay2241** [comment]
Hi Nikhil,

Campare using a google sheet. Then try to export visualisation in png format.

**Comment by Nikhil-lab** [comment]
While comparing using a google sheet, Export to png is not working. let me check
