### ISSUE TITLE
UI to show the urls of ASCT+B tables fore each organ

### ISSUE THREAD

**Issue by vutukuriajay2241** [hubmapconsortium/ccf-asct-reporter#318]
Currently, we have an open to view the Data tables  from Home page and  from  Nav bar.

Now, we wanted to show as dropdown menu instead of having single link in anchor tag.

I am planning to use a nested menu from [Angular Material](https://material.angular.io/components/menu/examples#menu-nested).
![image](https://user-images.githubusercontent.com/42532629/151431342-7458385c-35e3-4f89-ae77-06ccc9dee11d.png)

We also need to show all the tables in Docs sections of Reporter.

**Comment by bherr2** [comment]
Yeah, that looks like a good option. Note we could link to the individual tables even now (because each sheet_id+gid is a unique URL), which should help this issue to move forward independent of the table restructuring.

**Comment by bherr2** [comment]
(Also remember to put new issues on the sprint backlog :-) )

**Comment by vutukuriajay2241** [comment]
Sure Bruce, We can start this.
