### ISSUE TITLE
Feature Request: Launch in Playground mode

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#357]
@bherr2 @katyb @vutukuriajay2241 

Both of these suggestions I agree with wholeheartedly. 

For the first suggestion of launching without the need to first select an organ is a BIG one for me too. It's cumbersome. 

Begin forwarded message:

From: "Fisher, Stephen A" <safisher@sas.upenn.edu>
Date: March 23, 2022 at 9:24:43 AM EDT
To: HuBMAP CCF Info <infoccf@indiana.edu>
Subject: [External] Reporter

﻿
This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.

Hi All,

A few feature requests.

1. It would be nice to launch the reporter directly into Playground mode. As it stands I’m forced to first select an organ, when I open a new Reporter instance.

2. It would be helpful if you could wrap node names instead of truncating them with “…” (see attached), or offer text-wrap as an option.

Thanks,
Stephen

------------------------------------
Stephen Fisher, PhD
Biology Department
University of Pennsylvania
<img width="259" alt="Screen Shot 2022-03-23 at 1 21 58 PM" src="https://user-images.githubusercontent.com/47257000/160022197-ad8f9a7a-1662-4c1e-90d5-df7170702695.png">

**Comment by vutukuriajay2241** [comment]
For feature 1, we can do something like the below.

please let me know your thoughts on this idea.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/42532629/160053727-5244f5e1-806b-49b6-bcc3-5e08433c7674.png">

**Comment by emquardokus** [comment]
@vutukuriajay2241 this would be awesome!

**Comment by bherr2** [comment]
And easy enough to implement too. @emquardokus in the future, please separate out feature requests, especially when they are so different like above.

**Comment by bherr2** [comment]
Also @vutukuriajay2241 make sure this new button click is logged to google analytics as well to see how much it gets used when we add it.
