### ISSUE TITLE
Add 'Select All' button to the search

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-asct-reporter#39]
When the user types 'endo' for example, they would want to select all the structures that start with 'endo'. 

Therefore, add a feature to add a 'Select all' checkbox when something is typed.

**Comment by macvogelsang** [comment]
I'd like to get more information on the use-cases for this. We have "deselect all" which makes sense to reset the selection, but I don't see a value in selecting all. The visualization jumps to each structure as it is selected, but this same behavior in the select all case doesn't really make sense. Additionally, it's not clear why a user would need to highlight all structures starting with a common prefix, and the search results may include other unrelated structures as well (they would have to be deselected one by one). I think it's useful to highlight multiple structures at the same time, but this can already be done manually by clicking each one.
