### ISSUE TITLE
HRA release 4 (v1.3) ASCT+B tables submitted for publishing

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#515]
There are 13 tables submitted with revisions for HRA release 4 (v1.3) ASCT+B tables submitted for publishing

Blood_v1.3 | https://docs.google.com/spreadsheets/d/1wx2y8_t7NsAs8hPnr6u_N1QK8y_lC3t1G0DnD3LNUnQ/edit#gid=543201897
-- | --
Blood_Vasculature_v1.3 | https://docs.google.com/spreadsheets/d/1N2_rZBJEJHuy_pVgZUdGRbXHwz9rdRp2U-rLpVN7n3w/edit#gid=1789898267
Bone_Marrow_v1.3 | https://docs.google.com/spreadsheets/d/1prDIvvQF0akXKCfLv6FqjtQgZ_oKbIfSfMZt9twrfd0/edit#gid=771476671
Brain_v1.3 | https://docs.google.com/spreadsheets/d/1Hdd-llGhPZ4zFUq5nUyhTeDaPFgQYmEqk-Ch3E6xr-Q/edit#gid=2056967441
Eye_v1.2 | https://docs.google.com/spreadsheets/d/1qx6ljQipIYEjm9HoDweulJoRq4saKXGv16S5en8O4Rs/edit#gid=695483621
Heart_v1.2 | https://docs.google.com/spreadsheets/d/1eSzDzv_wOpMGTrSShmy_S7IXs8_H_Kp3QZg-gfKyUWk/edit#gid=1759721736
Large_Intestine_v1.3 | https://docs.google.com/spreadsheets/d/1DgN9i72VFDmGwynStGbhkpHfas_RA9ccIrDgI77ULJA/edit#gid=2043181688
Lymph_Vasculature_v1.2 | https://docs.google.com/spreadsheets/d/1x2U09QKAkxGFI4d24JN6YSzEZruYHJi96PlDIT3c1pU/edit#gid=2087685463
Ovary_v1.2 | https://docs.google.com/spreadsheets/d/1bPMrORa7CQa2JpVkRF_jHmA_GdS1qBryXl9riMZUBJU/edit#gid=756296951
Pancreas_v1.2 | https://docs.google.com/spreadsheets/d/1Ksn6FuMqIcZFXorMfM5gsuZugKESabQmwvIAwYksdRE/edit#gid=439021026
Small_Intestine_v1.1 | https://docs.google.com/spreadsheets/d/1pZDLDiAHD-QDi-OTF4GtUHf6bkKkDc2qc0eIFnIqS_s/edit#gid=247140941
Spleen_v1.3 | https://docs.google.com/spreadsheets/d/1AEKYXAKP1oRM2krnbU_Un89JfxYEm_gjjwwJTEt1SiI/edit#gid=69626346
Thymus_v1.3 | https://docs.google.com/spreadsheets/d/13VmRAofv85ZapJgmtHAVO67ICY4nK1FOugkTKV8_eoM/edit#gid=863370556

**Comment by emquardokus** [comment]
updated 13 tables for 4th release with gid

**Comment by bherr2** [comment]
Merged into develop
