### ISSUE TITLE
Playground: upload component modifications

### ISSUE THREAD

**Issue by libby-maier** [hubmapconsortium/ccf-asct-reporter#622]
# Playground: upload component modifications

![image](https://user-images.githubusercontent.com/97060856/227624773-aa540e07-98c1-40b8-abc5-f97649422fa3.png)

## To Do
- [x] Update the content of the instructions to the content specified in the Figma file.
- [x]  Add a divider, a "New" badge, and content to the instructions container
- [x]  Implement spacing and layout adjustments in the upload interface
- [x]  Color the asterisk after "Data" red
- [x]  Implement the Upload File button update
- [x]  Implement the No file loaded copy under the new Upload button

## Resources

- [Figma design file: Playground upload component](https://www.figma.com/file/u9SoNtpqNORA758srXVALQ/ASCT%2BB-Reporter?node-id=106-230&t=QfaUYntIWmFfibPy-4)
- OMAP Compare Template (Link to be added when it is delivered to me)

## User Stories
- As a user, I want to know what data I can upload into the Playground, so that I can generate useful visualizations and reports from the ASCT+B Reporter.
- As a user, I want to have helpful instructions, so that I can successfully use this feature.
- As a user, I want the upload component to be intuitive, so that I can quickly generate visualizations and reports that further my research.
- As a user, I want a button with an upload icon instead of a vague attachment icon without a label, so that I can learn how to use this interface faster.

**Comment by libby-maier** [comment]
# Component design update from 4/3 meeting

-  Design update from 4/3 meeting with @pbrm4 & @bherr2 
- Removed file title/description inputs
- Removed the delete (trash can icon) button
- Added bottom panel and submit button
- Updated positioning of the required field text

## Resources
- [Figma design file: Playground upload component](https://www.figma.com/file/u9SoNtpqNORA758srXVALQ/ASCT%2BB-Reporter?node-id=106-230&t=GxUC0Dc0ADYcS1Sq-4)

![image](https://user-images.githubusercontent.com/97060856/229570233-08d24c66-c389-42a0-9ebf-1f256ec5ba1a.png)

**Comment by pbrm4** [comment]
@bherr2 Fixed styling. Do let me know if i am missing anything else
