### ISSUE TITLE
typos & edits in the Master tables listing for new tables

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#628]
@bherr2 (I apparently do not have editing rights or I would have edited and sent a PR)

1) There is both "breast" and "mammary gland" pointing to the same v1.0 DRAFT table--do we need both links?

2) The Master table list has femoris spelled incorrectly as feromis In "quadriceps femoris" this file[projects/v2/src/assets/sheet-config.json](https://github.com/hubmapconsortium/ccf-asct-reporter/commit/c2b0c0db5835f0d7579dd42ddf27849c5f5ebe74#diff-a08225419551a24c4e18a5a961a53a091498e84dcb4ba8caad2e32a931b4da62)
<img width="156" alt="Screenshot 2023-03-31 at 4 33 12 AM" src="https://user-images.githubusercontent.com/47257000/229070931-2078ed20-833a-49bf-ab02-80f36c2ccfc4.png">

3) Placenta should be Placenta full term since we have another coming that will represent early stages

Thanks

**Comment by bherr2** [comment]
You should have edit access (and I double added you just in case), but you can always create a PR by forking and setting up a PR that way see [this article](https://ardalis.com/how-to-add-files-to-a-github-repo-you-don%E2%80%99t-own/)). 

first two are self-explanatory, but what do you want as the label for full term placenta? `Placenta (full term)`, `Placenta full term`, `full term placenta` or something else (casing matters)? (I will probably need to check to make sure the parenthesis don't break anything, but I think it'll be fine)

**Comment by bherr2** [comment]
@emquardokus ☝️

**Comment by emquardokus** [comment]
@bherr2 please see PR: https://github.com/hubmapconsortium/ccf-asct-reporter/pull/653
