### ISSUE TITLE
BUG: Exit playground leads to "Select one or more ASCT+B Tables"

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-asct-reporter#718]
When I was trying to use the Playground feature of the ASCT+B reporter, it would not accept an uploaded .csv without error. 
I double checked the table, adjusted as needed, tried again, but it still did not work. 
So when I then tried to "exit playground" instead of being dumped back into the Reporter, I ended up at the "Select one or more ASCT+B Tables" dialog instead of just being in the Reporter to try again using the playground.
If I clicked CANCEL on the diaglog, it just put me back in the error situation of the previous playground and I could NOT exit the playground. 
Only way out was completely going back to start window of selecting either "go to visualization" or "go to playground"

**Comment by emquardokus** [comment]
@libby-maier I don't know if this might be an artifact of the OMAP integration, but in case, can you look at Figma to see if somehow something got rewired inadvertently? Thank you!

**Comment by pbrm4** [comment]
@emquardokus I will look at this and update this issue if I find something.
