### ISSUE TITLE
Integrate Google Analytics for 2.0

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-asct-reporter#77]
# Google Analytics

Receiving feedback from what users interact with and use the most has always been important. Through Google Analytics, we hope to track the usage on the Reporter so as to get insights on what features and functionalities need to be improved upon

## Getting Started
1. Use an NPM package from here: https://www.npmjs.com/package/ngx-google-analytics OR 
2. A details guide as to how to set it up - https://medium.com/madhash/how-to-properly-add-google-analytics-tracking-to-your-angular-web-app-bc7750713c9e
3. For now use your own GCP GA ID. (It's free)

## How to use GA with Vega? 
Use the code snippet below to get the value from signals of the Vega graph,
```
let signalValue = this.treeView.signal('node__click')
treeView.runAsync();
```
Check out the [docs](https://vega.github.io/vega/docs/api/view/) for more info. Alternatively, you can reach out if you're stuck

## Event Tracking

The sheet linked here is the one that was used for adding GA to the Reporter v1.0. Create a google sheet that looks like this (you can edit this too) which covers the new/changed functionalities.

https://docs.google.com/spreadsheets/d/1nY89jasZqSWtKDwI0izXOsRZqdyqOjsGcRIPPvVEy-Y/edit#gid=0 

This google sheet will have all the events that need to be tracked. Please share it with me so that I can take a look at it.

### Note
Try to complete this by Apr 2. For now, you can create a GA ID via your personal Google account. When its approved and ready, I'll shift it to CNS' Google account.

Please let me know if you have any questions!

**Comment by macvogelsang** [comment]
Addressed in https://github.com/hubmapconsortium/ccf-asct-reporter/pull/81
