### ISSUE TITLE
Create separate count views for organs in the all organs visualization

### ISSUE THREAD

**Issue by hrishikeshpaul** [hubmapconsortium/ccf-asct-reporter#95]
In the report of the All organs visualization, show counts for each and every organ separately

**Comment by vutukuriajay2241** [comment]
Can you please brief more about the issue

**Comment by bherr2** [comment]
CC @katy need details to start this...

**Comment by bherr2** [comment]
CC @katyb need details to start this...

**Comment by bherr2** [comment]
Show even when "Show All AS" is off. Let me know if AS counts are difficult when its off.
